name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"   # Runs every day at 00:00
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate the snake
        uses: Platane/snk@master
        with:
          github_user_name: sanjaykumar156
          outputs: |
            ./github-contribution-grid-snake.svg
            ./github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Commit the changes
        uses: EndBug/add-and-commit@v9
        with:
          message: "Generate Contribution Snake"
          add: "*.svg"
